import type { Metadata } from "next";

import { LegalPage, type LegalSection } from "@/components/legal/LegalPage";

export const metadata: Metadata = {
  title: "Privacy Policy | Hempon Group",
  description: "Hempon Group's privacy policy.",
};

const sections: LegalSection[] = [
  { title: "1. Information We Collect", paragraphs: ["Depending on how you interact with our website and services, we may collect the following information:", "Information you provide directly", "This may include:"], bullets: ["Your name", "Email address", "Telephone number", "Company or organization name", "Project or service requirements", "Messages and enquiries submitted through our contact forms", "Information you provide when requesting a quotation or service", "Any other information you voluntarily provide to us"] },
  { title: "Information collected automatically", paragraphs: ["When you visit our website, certain technical information may be collected automatically, including:"], bullets: ["IP address", "Browser type and version", "Device type", "Operating system", "Pages visited", "Approximate location derived from technical information", "Date and time of visits", "Referring website or page", "Website interaction and usage information"] },
  { title: "2. How We Use Your Information", paragraphs: ["We may use information we collect to:"], bullets: ["Respond to enquiries and requests", "Provide quotations and proposals", "Deliver and manage our services", "Communicate with clients and prospective clients", "Develop, maintain, and improve our website", "Improve our products, services, and user experience", "Prevent fraud, abuse, and unauthorized activity", "Maintain website and information security", "Comply with applicable legal and regulatory obligations", "Keep appropriate business and service records"], afterBullets: ["We will not use your personal information for purposes that are incompatible with the purpose for which it was collected unless permitted or required by applicable law."] },
  { title: "3. Contact and Enquiry Information", paragraphs: ["If you contact us through our website, email, telephone, WhatsApp, or another communication channel, we may retain the information you provide in order to respond to your enquiry and manage our business relationship with you.", "You should avoid submitting sensitive or confidential information through a general website contact form unless we specifically request it and provide an appropriate secure channel."] },
  { title: "4. Cookies and Similar Technologies", paragraphs: ["Our website may use cookies and similar technologies to provide essential functionality, remember preferences, understand website usage, and improve performance.", "Cookies may be used for purposes such as:"], bullets: ["Website functionality", "Security", "Analytics", "Performance monitoring", "Remembering user preferences"], afterBullets: ["You can configure your browser to reject or delete cookies. However, disabling certain cookies may affect some website functionality.", "Where required by applicable law, we will seek appropriate consent before using non-essential cookies or similar technologies."] },
  { title: "5. Third-Party Services", paragraphs: ["We may use third-party providers to support our website and services. These providers may include services for:"], bullets: ["Website hosting", "Analytics", "Email delivery", "Payment processing", "Communication", "Security", "Cloud storage", "Website performance"], afterBullets: ["These providers may process information on our behalf and are expected to handle information in accordance with applicable contractual and legal requirements.", "Third-party websites or services linked from our website may have their own privacy policies. We are not responsible for the privacy practices of websites that we do not operate."] },
  { title: "6. How We Protect Your Information", paragraphs: ["We take reasonable technical and organizational measures to protect personal information against unauthorized access, alteration, disclosure, loss, misuse, or destruction.", "However, no internet transmission or electronic storage system can be guaranteed to be completely secure. We therefore cannot guarantee absolute security of information transmitted to or through our website."] },
  { title: "7. Data Retention", paragraphs: ["We retain personal information only for as long as reasonably necessary for the purposes for which it was collected, including providing services, maintaining business records, resolving disputes, enforcing agreements, and meeting legal or regulatory obligations.", "When information is no longer required, we may securely delete, anonymize, or otherwise dispose of it where appropriate."] },
  { title: "8. Your Privacy Rights", paragraphs: ["Subject to applicable law, you may have rights concerning your personal information, including the right to:"], bullets: ["Request access to personal information we hold about you", "Request correction of inaccurate or incomplete information", "Request deletion of personal information in appropriate circumstances", "Object to certain processing of your information", "Request restriction of processing in applicable circumstances", "Withdraw consent where processing is based on consent", "Raise a concern or complaint regarding how your information is handled"], afterBullets: ["Some rights may be subject to legal or contractual limitations."] },
  { title: "9. Kenya Data Protection", paragraphs: ["Hempon Group aims to handle personal information in accordance with applicable data protection laws, including the Data Protection Act, 2019 of Kenya, where applicable.", "Where required, we will apply appropriate safeguards when collecting, using, storing, or transferring personal information."] },
  { title: "10. Children's Privacy", paragraphs: ["Our website and services are not intentionally directed toward children.", "We do not knowingly collect personal information from children without appropriate authorization or a lawful basis.", "If you believe that a child has provided personal information to us without appropriate authorization, please contact us so that we can take appropriate action."] },
  { title: "11. Changes to This Privacy Policy", paragraphs: ["We may update this Privacy Policy from time to time to reflect changes in our services, technology, legal requirements, or business practices.", "When we make changes, we will update the Last Updated date at the top of this page.", "We encourage you to periodically review this page for the latest version."] },
  { title: "12. Contact Us", paragraphs: [<>If you have questions about this Privacy Policy, your personal information, or our privacy practices, please contact us:</>, <><strong>Hempon Group</strong><br />Email: <a className="text-primary underline underline-offset-4" href="mailto:hempongroup@gmail.com">hempongroup@gmail.com</a><br />Website: <a className="text-primary underline underline-offset-4" href="https://hempon-group.vercel.app">https://hempon-group.vercel.app</a><br />Phone: <a className="text-primary underline underline-offset-4" href="tel:+254738219953">+254 738 219 953</a><br />Location: Mombasa, Kenya</>, <><strong>Data Protection Contact:</strong> Contact Hempon Group using the details above.</>] },
];

export default function PrivacyPolicyPage() {
  return <LegalPage title="Privacy Policy" intro={["Hempon Group (\"Hempon Group\", \"we\", \"us\", or \"our\") respects your privacy and is committed to protecting the personal information you provide when you use our website, services, or communicate with us.", "This Privacy Policy explains what information we collect, how we use it, how we protect it, and the choices you have regarding your information."]} sections={sections} closing="By using our website, you acknowledge that you have read and understood this Privacy Policy." />;
}
