import type { Metadata } from "next";

import { LegalPage, type LegalSection } from "@/components/legal/LegalPage";

export const metadata: Metadata = {
  title: "Terms of Service | Hempon Group",
  description: "Hempon Group's terms of service.",
};

const sections: LegalSection[] = [
  { title: "1. About Hempon Group", paragraphs: ["Hempon Group (\"Hempon Group\", \"we\", \"us\", or \"our\") provides technology and digital services, which may include:", "The specific services provided to a client will depend on the applicable proposal, quotation, statement of work, agreement, or other written arrangement."], bullets: ["Website design and development", "Web application development", "UI/UX design", "Website maintenance", "Digital automation", "Technology consulting", "Software development", "Hosting and deployment assistance", "Graphic and digital design", "Other technology-related services"] },
  { title: "2. Use of Our Website", paragraphs: ["You agree to use our website only for lawful purposes.", "You must not:", "We reserve the right to restrict or terminate access to our website where we reasonably believe that these Terms have been violated."], bullets: ["Use the website for fraudulent or unlawful activities", "Attempt to gain unauthorized access to our systems", "Introduce malicious software or harmful code", "Interfere with the operation or security of the website", "Copy or misuse website content without permission", "Impersonate another person or organization", "Use our services to facilitate illegal activities", "Attempt to disrupt or compromise our infrastructure"] },
  { title: "3. Our Services", paragraphs: ["Information displayed on our website is provided for general informational purposes.", "Specific project requirements, deliverables, timelines, prices, payment terms, revisions, support arrangements, and other obligations will be agreed upon separately with the client.", "A quotation, proposal, invoice, statement of work, or service agreement may contain additional terms that apply to a particular project.", "Where a specific written agreement conflicts with these general Terms, the specific agreement will generally take precedence for that project."] },
  { title: "4. Quotes and Pricing", paragraphs: ["Any prices displayed on our website or communicated informally are subject to change unless expressly stated otherwise.", "A quotation may specify:", "Work may commence after the required approval, deposit, or payment has been received, as specified in the applicable agreement."], bullets: ["Project scope", "Deliverables", "Pricing", "Payment schedule", "Estimated timelines", "Number of revisions", "Hosting or third-party costs", "Maintenance or support arrangements"] },
  { title: "5. Client Responsibilities", paragraphs: ["Clients are responsible for providing accurate and timely information, content, materials, credentials, approvals, and feedback reasonably required to complete a project.", "This may include:", "Delays in receiving required information or approvals may affect project timelines."], bullets: ["Logos and branding", "Text and written content", "Images and media", "Product or service information", "Domain and hosting information", "Required approvals", "Access to third-party platforms"] },
  { title: "6. Intellectual Property", paragraphs: ["Unless otherwise agreed in writing, Hempon Group retains ownership of its pre-existing:", "Client-specific deliverables may be transferred or licensed to the client according to the applicable project agreement and payment terms.", "Third-party software, fonts, images, icons, plugins, libraries, and other assets remain subject to their respective licenses and terms."], bullets: ["Code", "Frameworks", "Templates", "Libraries", "Development tools", "Design systems", "Components", "Internal processes", "Reusable technical solutions"] },
  { title: "7. Client Content", paragraphs: ["You retain responsibility for content, data, images, trademarks, documents, and other materials that you provide to us.", "You represent that you have the necessary rights, permissions, or licenses to use materials supplied to us for a project.", "You agree not to provide materials that infringe another person's intellectual property, privacy, or other legal rights."] },
  { title: "8. Third-Party Services", paragraphs: ["Some projects may depend on third-party services such as:", "We are not responsible for outages, price changes, policy changes, limitations, security incidents, or other failures caused by third-party providers outside our reasonable control."], bullets: ["Hosting providers", "Domain registrars", "Payment processors", "Email providers", "Cloud platforms", "APIs", "Plugins", "Software libraries", "Analytics services"] },
  { title: "9. Project Timelines", paragraphs: ["Project timelines are estimates unless a specific deadline has been expressly agreed upon in writing.", "Timelines may be affected by:"], bullets: ["Changes in project scope", "Delayed client feedback", "Delayed content or approvals", "Third-party services", "Technical issues", "Force majeure events", "Additional requirements requested during development"] },
  { title: "10. Changes to Project Scope", paragraphs: ["Requests that materially change an agreed project scope may result in additional costs or changes to the delivery timeline.", "Where appropriate, additional work will be discussed and approved before implementation."] },
  { title: "11. Payments", paragraphs: ["Payment terms will be specified in the relevant quotation, invoice, proposal, or service agreement.", "Unless otherwise agreed, failure to make required payments may result in suspension of work or services.", "Any applicable deposits, milestone payments, subscriptions, hosting charges, maintenance fees, or other charges will be communicated before they become due."] },
  { title: "12. Warranties and Disclaimers", paragraphs: ["We aim to provide professional and reliable services. However, websites, applications, software, hosting services, and internet-based systems may be affected by circumstances beyond our control.", "To the extent permitted by applicable law, we do not guarantee that:", "Nothing in these Terms excludes any rights or protections that cannot lawfully be excluded under applicable law."], bullets: ["The website will always be available", "Services will be completely error-free", "Third-party services will always operate without interruption", "Software will be completely free from defects or vulnerabilities", "The website will produce a particular business or financial result"] },
  { title: "13. Limitation of Liability", paragraphs: ["To the maximum extent permitted by applicable law, Hempon Group will not be liable for indirect, incidental, consequential, special, or unforeseeable losses arising from the use of our website or services.", "This may include loss of profits, business interruption, loss of data, or loss of business opportunities, except where liability cannot legally be excluded.", "Nothing in these Terms limits liability where such limitation is prohibited by applicable law."] },
  { title: "14. Website Content", paragraphs: ["The content on this website, including text, graphics, branding, layouts, illustrations, photographs, code, and other materials, may be protected by intellectual property laws.", "You may not reproduce, redistribute, modify, sell, or commercially exploit our website content without our prior written permission, except where permitted by law."] },
  { title: "15. Portfolio and Client Work", paragraphs: ["Where agreed or where legally permitted, Hempon Group may display completed projects, screenshots, designs, or descriptions of work in its portfolio and marketing materials.", "If a project is subject to confidentiality or a non-disclosure agreement, we will respect the applicable restrictions."] },
  { title: "16. Confidentiality", paragraphs: ["Information identified as confidential and shared during a business or project relationship should be treated appropriately and not disclosed to unauthorized third parties.", "Specific confidentiality obligations may be governed by a separate non-disclosure agreement or service contract."] },
  { title: "17. Termination", paragraphs: ["Either party may terminate a project or service arrangement according to the applicable written agreement.", "We may suspend or terminate access to our website or services if you:", "Termination does not automatically eliminate obligations that arose before termination."], bullets: ["Seriously breach these Terms", "Engage in unlawful activity", "Attempt to compromise our systems", "Fail to meet applicable payment obligations", "Misuse our services"] },
  { title: "18. Changes to These Terms", paragraphs: ["We may update these Terms from time to time.", "The updated version will be posted on this website with a revised Last Updated date.", "Your continued use of the website following an update constitutes acceptance of the updated Terms to the extent permitted by applicable law."] },
  { title: "19. Governing Law", paragraphs: ["These Terms shall be governed by and interpreted in accordance with the laws of Kenya, unless applicable law requires otherwise.", "Any disputes will be handled in accordance with the applicable laws and procedures of Kenya."] },
  { title: "20. Contact Us", paragraphs: [<>If you have questions about these Terms, please contact us:</>, <><strong>Hempon Group</strong><br />Email: <a className="text-primary underline underline-offset-4" href="mailto:hempongroup@gmail.com">hempongroup@gmail.com</a><br />Website: <a className="text-primary underline underline-offset-4" href="https://hempon-group.vercel.app">https://hempon-group.vercel.app</a><br />Phone: <a className="text-primary underline underline-offset-4" href="tel:+254738219953">+254 738 219 953</a><br />Location: Mombasa, Kenya</>] },
];

export default function TermsPage() {
  return <LegalPage title="Terms of Service" intro={["Welcome to Hempon Group.", "These Terms of Service (\"Terms\") govern your use of the Hempon Group website and the digital products and services we provide.", "By accessing or using our website, you agree to these Terms. If you do not agree with these Terms, please do not use our website or services."]} sections={sections} closing="Thank you for using Hempon Group." />;
}
